// Reused from Atelier — Atelier reads/writes these on the same contract

export interface Milestone {
  description: string;
  amount: string;
  status: "pending" | "submitted" | "approved" | "rejected" | "disputed" | "resolved";
  submittedAt?: number;
  approvedAt?: number;
  rejectionReason?: string;
}

export interface Escrow {
  id: string;
  payer: string; // Atelier's Agent Wallet address
  beneficiary: string; // hired freelancer
  token: string;
  totalAmount: string;
  releasedAmount: string;
  status: "pending" | "active" | "completed" | "disputed" | "cancelled" | "refunded" | "expired";
  createdAt: number;
  duration: number;
  deadlineAt?: number;
  milestones: Milestone[];
  projectTitle?: string;
  projectDescription?: string;
  isOpenJob?: boolean;
  applications?: Application[];
  applicationCount?: number;
}

export interface Application {
  freelancerAddress: string;
  coverLetter: string;
  proposedTimeline: number;
  appliedAt: number;
  status: "pending" | "accepted" | "rejected";
}

// Atelier-specific types

export interface AtelierTask {
  id: string;
  instruction: string; // raw client input — from an AI agent (x402) or a human (UI)
  clientType: "agent" | "human";
  brief: AcceptanceBrief; // generated by the LLM brain (see daemon/src/groq/structured.ts)
  escrowId?: string; // set after job is posted on-chain
  status: "briefing" | "posted" | "reviewing" | "active" | "reviewing_work" | "completed" | "failed";
  createdAt: number;
}

export interface BriefMilestone {
  description: string;
  amount: number; // in USDC
}

export interface AcceptanceBrief {
  title: string;
  budget: number; // in USDC
  durationDays: number;
  criteria: string[]; // explicit acceptance checklist (5-8 items)
  deliverableFormat: string; // e.g. "SVG + PNG, min 1000x1000px"
  revisionRounds: number; // max revisions before human escalation
  /** Minutes the job stays open for applications before they are judged together. */
  applicationWindowMinutes?: number;
  /**
   * False when the title names work the description does not describe.
   *
   * The brief is always written from the description — the title is a label a
   * client typed and may be shorthand or simply wrong. When the two genuinely
   * disagree, only the client can say which they meant, so it is reported
   * rather than resolved.
   */
  titleMatchesWork?: boolean;
  /** One sentence naming what each of the two implies. Empty when they agree. */
  titleConflict?: string;
  milestones: BriefMilestone[]; // splits the budget into independently-reviewed chunks
  briefHash?: `0x${string}`; // keccak256 of criteria JSON, posted on-chain in projectDescription
}

export interface AgentDecision {
  id: string;
  /** The on-chain Atelier escrowId (as a string) — not AtelierTask.id. Every
   *  decision after brief generation is scoped to an escrow, so this is what
   *  actually correlates decisions/payments to a task via task.escrowId. */
  taskId: string;
  type:
    | "brief_generated"
    | "application_scored"
    | "applicant_accepted"
    | "no_suitable_applicant"
    | "portfolio_verified"
    | "work_approved"
    | "work_rejected"
    | "escalated";
  reasoning: string; // the LLM's written explanation
  target?: string; // freelancer address if applicable
  score?: number; // 0-100 for application scoring
  timestamp: number;
}
